theme: jekyll-theme-architect
title: Shanghai Interscholastic Ethics Bowl 2020
description: February 10th, HSEFZ
show_downloads: true
github:
  zip_url: https://sieb2020.github.io/resources/
  tar_url: https://sieb2020.github.io/resources/
  owner_url: https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAACbSkXpUQTk4TjI3NEswMDVNNU5DMTNEVlo3UEVJUy4u
